Razor_to_DependencyInjection/Models/ErrorViewModel.cs
namespace Razor_to_DependencyInjection.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Razor_to_DependencyInjection/Models/Person.cs
namespace Razor_to_DependencyInjection.Models
{
    public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
    }
}

Razor_to_DependencyInjection/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Razor_to_DependencyInjection.Models;
using ServiceDL;
using ServiceInterfaces;
using System.Diagnostics;

namespace Razor_to_DependencyInjection.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        //=========================================================================
        //========================== Section = RazarPage ==========================
        //=========================================================================
        #region RazaarPage
        //========= class 1,2 =====
        //MVC Archetecure   Model , View , Controller
        //=========

        //========= class 3 CodeBlock in View =====
        //=========

        //========= class 4 ,5,6,7 ,8 =====
        //Switcht stetmtn
        //Foreach
        //forloop,
        //littral
        //loacl Fn

        //========= class 9, html.Raw() ========
        //html.Raw("<div><i>Pakistan</i></div>")
        //=========

        //========= class 10,11,12 ========
        //Send data from View To controller
        //=========

        //========= class 13,14, =========
        //strongly type model
        //=========

        //========= class 15 =========
        //VM
        //=========

        //========= class 16 =========
        //View IMport
        //=========
        #endregion

        //=========================================================================
        //========================== Section = Layout ==========================
        //=========================================================================
        #region Layout
        //Time bacaaoo or agaaa nekal jaoo
        #endregion

        //=========================================================================
        //========================== Section = PartialView ==========================
        //=========================================================================
        #region PartialView
        //Time bacaaoo or agaaa nekal jaoo
        #endregion

        //=========================================================================
        //========================== Section = ViewComponent ==========================
        //=========================================================================
        #region View_Compoentn
        //======= Class 1 =======
        //Create View_Comonent (async)
        //Add partialView of compnete Default.cshtml
        //Change name of  partialView --> then Add name from component return
        //=======================

        //======= class 5 =====
        //showing Viewcompanent using Jquery
        public IActionResult ViewComponentByActinResul()
        {
            Person p = new Person();
            List<Person> pList = new List<Person>()
            {
                new Person(){Id = 1,Name = "Saqib" , Address = "abc"},
                new Person(){Id = 2,Name = "A" , Address = "abc"},
                new Person(){Id = 3,Name = "B" , Address = "abc"},
                new Person(){Id = 4,Name = "C" , Address = "abc"},
                new Person(){Id = 5,Name = "D" , Address = "abc"},
            };

            return ViewComponent("Person",pList);
        }
        #endregion


        //=========================================================================
        //========================== Section = Dependency Inject ==========================
        //=========================================================================
        #region DI
        //======= Class 1 =======
        private readonly ICitiesService _cities;
        public HomeController(ICitiesService cities)
        {
            _cities = cities;
        }
        public IActionResult GetCityList()
        {
            //CitiesService _citiesService = new CitiesService();
            //var list = _citiesService.getAllList();
            var list = _cities.getAllList();
            return View(list);
        }
        #endregion


        //=========================================================================
        //========================== Section = Envirment ==========================
        //=========================================================================
        #region Envirment
        //Enirment are used in Working ,with  Program (startup) file
        //===== 1. Developement Enirment =========
        //This environment is where software developers write, test, and debug code. It is often a local setup on developers' machines or a dedicated development server. In this environment, developers have the flexibility to experiment, make changes, and troubleshoot without affecting the actual users or the live system

        //===== 2. Staging Enirment =========
        //The staging environment is used as a pre-production environment that closely resembles the production environment. It serves as a testing ground where the application is deployed before being released to production. 

        //===== 3. Production Enirment =========
        //The production environment is where the application is deployed and made available to end-users.
        #endregion


        //=========================================================================
        //========================== Section = Configuration (Importent) ==========================
        //=========================================================================
        #region Configuration_in_ProgramFile
        //Please go to program file
        #endregion
    }
}

Razor_to_DependencyInjection/ViewComponents/GridViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Razor_to_DependencyInjection.ViewComponents
{
    public class GridViewComponent:ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            //Different name of partialView("Grid")
            return View("Grid");
        }
    }
}

Razor_to_DependencyInjection/ViewComponents/NameViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Razor_to_DependencyInjection.ViewComponents
{
    public class NameViewComponent:ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
            //this component search or invoke partialView at this location
            //shared/Components/NameASMatch/Default.cshtml
            //________ Note _____
            //if we gave different name to view then we have to gave complete 
        }
    }
}

Razor_to_DependencyInjection/ViewComponents/PersonViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Razor_to_DependencyInjection.Models;

namespace Razor_to_DependencyInjection.ViewComponents
{
    public class PersonViewComponent:ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(List<Person> p)
        {
            return View("Person",p);
        }
    }
}

Razor_to_DependencyInjection/Views/Home/GetCityList.cshtml
@model List<string>
@{
    ViewData["Title"] = "Home Page";
}
@foreach (var item in Model)
{

    <div class="text-center">
        <h1 class="display-4">@item</h1>
    </div>
}

Razor_to_DependencyInjection/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>


<h1>___ Calling ViewComponent here ___</h1>
@await Component.InvokeAsync("Name")

<h1>___ Grid ViewComponent here ___</h1>
@await Component.InvokeAsync("Grid")

Razor_to_DependencyInjection/Views/Shared/Components/Grid/Grid.cshtml
<div class="card bg-primary text-white">
    <h1 class="display-4">Grid</h1>
    <table class="table table-dark">
        <thead>
            <tr>
                <th>#</th>
                <th>Id</th>
                <th>Name</th>
                <th>Contact</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>1</th>
                <th>1001</th>
                <th>SAQIB</th>
                <th>03243423</th>
            </tr>
            <tr>
                <th>2</th>
                <th>1002</th>
                <th>SAQIB</th>
                <th>03243423</th>
            </tr>
            <tr>
                <th>3</th>
                <th>1003</th>
                <th>SAQIB</th>
                <th>03243423</th>
            </tr>
            <tr>
                <th>1</th>
                <th>1001</th>
                <th>SAQIB</th>
                <th>03243423</th>
            </tr>
        </tbody>
    </table>
</div>

Razor_to_DependencyInjection/Views/Shared/Components/Name/Default.cshtml
<div class="card bg-primary text-white">
    <h1 class="display-4">Name Component</h1>
</div>

Razor_to_DependencyInjection/Views/Shared/Components/Person/Person.cshtml
@model IList<Person>
<div class="card bg-primary text-white">
    <h1 class="display-4">Person </h1>
    <table class="table table-dark">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Contact</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th>@item.Id</th>
                    <th>@item.Name</th>
                    <th>@item.Address</th>
                </tr>
            }
        </tbody>
    </table>
</div>

Razor_to_DependencyInjection/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Razor_to_DependencyInjection</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Razor_to_DependencyInjection.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Razor_to_DependencyInjection</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Razor_to_DependencyInjection - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>